maps = {
	1: {
	level:1,
		grid : {
			1: {
				2: {imgX:10, imgY:0, hitbox:true},
				3: {imgX:10, imgY:1, hitbox:true},
				4: {imgX:10, imgY:1, hitbox:true},
				5: {imgX:10, imgY:1, hitbox:true},
				6: {imgX:10, imgY:1, hitbox:true},
				8: {imgX:8, imgY:4, hitbox:false},
				9: {imgX:8, imgY:4, hitbox:false},
				10: {imgX:8, imgY:4, hitbox:false},
			},
			2: {
				2: {imgX:11, imgY:0, hitbox:true},
				3: {imgX:11, imgY:1, hitbox:true},
				4: {imgX:11, imgY:1, hitbox:true},
				5: {imgX:11, imgY:1, hitbox:true},
				6: {imgX:11, imgY:1, hitbox:true},
				8: {imgX:8, imgY:4, hitbox:false},
				9: {imgX:8, imgY:4, hitbox:false},
				10: {imgX:8, imgY:4, hitbox:false},
			},
			3: {
				1: {imgX:14, imgY:2, hitbox:false},
				2: {imgX:11, imgY:0, hitbox:true},
				3: {imgX:11, imgY:1, hitbox:true},
				4: {imgX:11, imgY:1, hitbox:true},
				5: {imgX:11, imgY:1, hitbox:true},
				6: {imgX:11, imgY:1, hitbox:true},
				8: {imgX:8, imgY:4, hitbox:false},
				9: {imgX:8, imgY:4, hitbox:false},
				10: {imgX:8, imgY:4, hitbox:false},
			},
			4: {
				1: {imgX:15, imgY:2, hitbox:false},
				2: {imgX:11, imgY:0, hitbox:true},
				3: {imgX:11, imgY:1, hitbox:true},
				4: {imgX:11, imgY:1, hitbox:true},
				5: {imgX:11, imgY:1, hitbox:true},
				6: {imgX:11, imgY:1, hitbox:true},
				7: {imgX:14, imgY:0, hitbox:false},
				8: {imgX:8, imgY:4, hitbox:false},
				9: {imgX:8, imgY:4, hitbox:false},
				10: {imgX:8, imgY:4, hitbox:false},
			},
			5: {
				1: {imgX:16, imgY:2, hitbox:false},
				2: {imgX:12, imgY:0, hitbox:true},
				3: {imgX:12, imgY:1, hitbox:true},
				4: {imgX:12, imgY:1, hitbox:true},
				5: {imgX:12, imgY:1, hitbox:true},
				6: {imgX:12, imgY:1, hitbox:true},
				7: {imgX:15, imgY:0, hitbox:false},
			},
			6: {
				7: {imgX:16, imgY:1, hitbox:false},
			},
			7: {
				6: {imgX:13, imgY:2, hitbox:true},
				7: {imgX:13, imgY:3, hitbox:true},
				8: {imgX:13, imgY:3, hitbox:true},
			},
			8: {
				6: {imgX:13, imgY:0, hitbox:true},
				7: {imgX:13, imgY:1, hitbox:true},
				8: {imgX:13, imgY:1, hitbox:true},
			},
			11: {
				0: {imgX:7, imgY:4, hitbox:false},
				1: {imgX:7, imgY:5, hitbox:false},
				2: {imgX:7, imgY:5, hitbox:false},
				3: {imgX:7, imgY:5, hitbox:false},
				4: {imgX:7, imgY:5, hitbox:false},
				5: {imgX:7, imgY:5, hitbox:false},
				6: {imgX:7, imgY:5, hitbox:false},
				7: {imgX:7, imgY:5, hitbox:false},
				8: {imgX:7, imgY:5, hitbox:false},
				9: {imgX:7, imgY:5, hitbox:false},
				10: {imgX:7, imgY:5, hitbox:false},
				11: {imgX:7, imgY:5, hitbox:false},
				12: {imgX:7, imgY:5, hitbox:false},
				13: {imgX:7, imgY:6, hitbox:false},
			},
			13: {
				3: {imgX:14, imgY:4, hitbox:false},
				4: {imgX:14, imgY:4, hitbox:false},
				5: {imgX:14, imgY:4, hitbox:false},
				6: {imgX:14, imgY:4, hitbox:false},
				8: {imgX:16, imgY:6, hitbox:false},
				9: {imgX:16, imgY:6, hitbox:false},
				10: {imgX:16, imgY:6, hitbox:false},
				11: {imgX:16, imgY:6, hitbox:false},
			},
			14: {
				3: {imgX:14, imgY:4, hitbox:false},
				4: {imgX:14, imgY:4, hitbox:false},
				5: {imgX:14, imgY:4, hitbox:false},
				6: {imgX:14, imgY:4, hitbox:false},
				8: {imgX:16, imgY:6, hitbox:false},
				9: {imgX:16, imgY:6, hitbox:false},
				10: {imgX:16, imgY:6, hitbox:false},
				11: {imgX:16, imgY:6, hitbox:false},
			},
			15: {
				3: {imgX:14, imgY:4, hitbox:false},
				4: {imgX:14, imgY:4, hitbox:false},
				5: {imgX:14, imgY:4, hitbox:false},
				6: {imgX:14, imgY:4, hitbox:false},
				8: {imgX:16, imgY:6, hitbox:false},
				9: {imgX:16, imgY:6, hitbox:false},
				10: {imgX:16, imgY:6, hitbox:false},
				11: {imgX:16, imgY:6, hitbox:false},
			},
		}
	}
}